# Unique project identifier in SonarQube
sonar.projectKey=my-python-app
sonar.projectName=My Python App
sonar.projectVersion=1.0

# Path to the source code (relative to this file)
sonar.sources=.
sonar.host.url=http://13.49.74.112:9000

# Language and Python version
sonar.language=py
sonar.python.version=3.9