name: Learning github actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout stage
        uses: actions/checkout@v7
      - name: Build python
        run: python app.py