name: Testing runner works

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build
        run: python3 app.py

  Docker:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Docker login
        uses: docker/login-action@v4
        with:
          username: ${{vars.DOCKERHUB_LOGIN}}
          password: ${{secrets.DOCKERLOGIN_PASSWORD}}
      - name: Docker build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: akshaykkdocker623/pythonapp:v2
